nelmio_api_doc:
    documentation:
        info:
            title: Lektoriym Blog API Doc
            description: Lektoriym Blog using Symfony framework
            version: 1.0.1
        securityDefinitions:
            ApiAuth:
                type: apiKey
                in: header
                name: x-api-key
    areas:
        path_patterns:
            - ^/api(?!/doc$)
