nelmio_api_doc:
    areas:
        path_patterns:
            - ^/api(?!/doc$)
    documentation:
        info:
            title: Lektoriym Blog API Doc
            description: Lektoriym Blog using Symfony framework
            version: 1.0.1
        securityDefinitions:
            ApiAuth:
                type: apiKey
                in: header
                name: x-api-key
        paths:
            /api/user/registration:
                post:
                    tags:
                        - User API
                    description: Registration new user
                    produces:
                        - application/json
                    parameters:
                        - name: user
                          description: User to be registered
                          in: body
                          required: true
                          schema:
                              type: object
                              properties:
                                  firstName:
                                      type: string
                                      example: fake_firstName
                                  lastName:
                                      type: string
                                      example: fake_lastName
                                  email:
                                      type: string
                                      example: fake_mail@mail.ua
                                  plainPassword:
                                      type: string
                                      example: fake_password
                                  region:
                                      type: string
                                      example: UA
                                  avatar_name:
                                      type: string
                                      example: default_avatar.jpg
                    responses:
                        '200':
                            description: Registration successful
                            schema:
                                type: object
                                properties:
                                    id:
                                      type: string
                                      example: 1
                                    firstName:
                                      type: string
                                      example: firstName
                                    lastName:
                                      type: string
                                      example: lastName
                                    email:
                                      type: string
                                      example: email@mail.ua
                                    region:
                                      type: string
                                      example: UA
                                    avatar_name:
                                      type: string
                                      example: default_avatar.jpg
                                    api-token:
                                        type: string
                                        example: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
                        '400':
                            description: Bad request
            /api/user/login:
                post:
                    tags:
                        - User API
                    description: Login into the api
                    produces:
                        - application/json
                    parameters:
                        - name: user
                          description: User object used for user authentication
                          in: body
                          required: true
                          schema:
                              type: object
                              properties:
                                  email:
                                      type: string
                                      example: moroztaras@i.ua
                                  plainPassword:
                                      type: string
                                      example: moroztaras
                    responses:
                        '200':
                            description: Login successful. Returns user profile
                            schema:
                                type: object
                                properties:
                                    id:
                                      type: string
                                      example: 1
                                    firstName:
                                      type: string
                                      example: firstName
                                    lastName:
                                      type: string
                                      example: lastName
                                    email:
                                      type: string
                                      example: email@mail.ua
                                    region:
                                      type: string
                                      example: UA
                                    avatar_name:
                                      type: string
                                      example: default_avatar.jpg
                                    api-token:
                                        type: string
                                        example: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
                        '400':
                            description: Authentication error
            /api/user/profile:
                get:
                    tags:
                        - User API
                    description: Profile user into the api
                    produces:
                        - application/json
                    parameters:
                        - name:  x-api-key
                          description: X-APPI-KEY
                          in: header
                          required: true
                    responses:
                        '200':
                            description: Returns user profile
                            schema:
                                type: object
                                properties:
                                    id:
                                      type: string
                                      example: 1
                                    firstName:
                                      type: string
                                      example: firstName
                                    lastName:
                                      type: string
                                      example: lastName
                                    email:
                                      type: string
                                      example: email@mail.ua
                                    region:
                                      type: string
                                      example: UA
                                    avatar_name:
                                      type: string
                                      example: default_avatar.jpg
                                    api-token:
                                        type: string
                                        example: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
                        '400':
                            description: Authentication error
            /api/articles:
                post:
                    tags:
                        - Articles API
                    description: Create new article
                    produces:
                        - application/json
                    parameters:
                        - name:  x-api-key
                          description: X-APPI-KEY
                          in: header
                          required: true
                        - name: article
                          description: Article object used for create article
                          in: body
                          required: true
                          schema:
                              type: object
                              properties:
                                  title:
                                      type: string
                                      example: New title for new articles
                                  text:
                                      type: string
                                      example: New fake text for new articles
                                  imageName:
                                      type: string
                                      example: article_image.jpg
                    responses:
                        '200':
                            description: New article successful
                            schema:
                                type: object
                                properties:
                                    article:
                                        type: object
                                        properties:
                                            id:
                                                type: string
                                                example: 1
                                            title:
                                                type: string
                                                example: New title for new articles
                                            text:
                                                 type: string
                                                 example: New fake text for new articles
                                            image:
                                                 type: string
                                                 example: article_image.jpg
                                            createdAt:
                                                 type: string
                                                 example: "2019-01-24T14:22:51+02:00"
                                            approved:
                                                 type: string
                                                 example: true
                                            likes:
                                                 type: string
                                                 example: 0
                        '400':
                            description: Authentication error
            /api/articles/page={page}:
                get:
                    tags:
                        - Articles API
                    description: Articles list
                    produces:
                        - application/json
                    parameters:
                        - name: page
                          description: Page for list articles
                          in: path
                          required: true
                          type: string
                    responses:
                        '200':
                            description: Articles list successful
                            schema:
                                type: object
                                properties:
                                    articles:
                                        type: object
                                        properties:
                                            id:
                                                type: string
                                                example: 1
                                            title:
                                                type: string
                                                example: Title artile 1
                                            text:
                                                 type: string
                                                 example: Text artile 1
                                            image:
                                                 type: string
                                                 example: article_image.jpg
                                            createdAt:
                                                 type: string
                                                 example: "2019-01-24T14:22:51+02:00"
                                            approved:
                                                 type: string
                                                 example: true
                                            likes:
                                                 type: string
                                                 example: 1
                        '400':
                            description: Bad request
            /api/articles/{id}:
                get:
                    tags:
                        - Articles API
                    description: Articles show
                    produces:
                        - application/json
                    parameters:
                        - name: id
                          description: Id for show article
                          in: path
                          required: true
                          type: string
                    responses:
                        '200':
                            description: Article show successful
                            schema:
                                type: object
                                properties:
                                    article:
                                        type: object
                                        properties:
                                            id:
                                                type: string
                                                example: 1
                                            title:
                                                type: string
                                                example: Title artile 1
                                            text:
                                                 type: string
                                                 example: Text artile 1
                                            image:
                                                 type: string
                                                 example: article_image.jpg
                                            createdAt:
                                                 type: string
                                                 example: "2019-01-24T14:22:51+02:00"
                                            approved:
                                                 type: string
                                                 example: true
                                            likes:
                                                 type: string
                                                 example: 1
                        '400':
                            description: Bad request
                        '404':
                            description: Article not found
