vich_uploader:
    db_driver: orm

    mappings:
        article_image:
            uri_prefix: /images/articles
            upload_destination: '%kernel.project_dir%/public/images/articles'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        user_avatar:
            uri_prefix: /images/users/avatars
            upload_destination: '%kernel.project_dir%/public/images/users/avatars'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
