#index:
#    path: /
#    controller: App\Controller\ArticleController::indexAction

app_logout:
  path: /logout

login_check:
    path: /login_check

app_preview:
  path: /preview
  controller: App\Controller\PageController::preview
